### ISSUE TITLE
Strange behaviour in Chrome

### ISSUE THREAD

**Issue by pietrogregorini** [verlok/lazyload#232]
I guess this is a bug. You can check it out in this published website here:
https://www.soloincartolina.it/cartoline/

If you scroll down fast on the page and then stop somewhere, the plugin stops loading the images. It seems like it's stuck somehow, instead of loading the images.

Any suggestions?
Thanks!

(Last version of LazyLoad 10.14.0 but also the previous one, Chrome 68)

**Comment by verlok** [comment]
Ciao Pietro,
thanks for reporting this. 
It looks like you have a scrolling container which is not the `document` element but the `#wrapper`.

```css
#wrapper {
    background: #ffffff;
    bottom: 2vw;
    left: 2vw;
    overflow-y: scroll;
    -webkit-overflow-scrolling: touch;
    position: fixed;
    right: 2vw;
    top: 2vw;
    z-index: 2;
}
```

Take a look at the [single container demo](demos/single_container.html). You should pass the scrolling container in LazyLoad's options.

Something like:

```js
var wrapper = document.getElementById("wrapper");
new LazyLoad({
    container: wrapper, 
    elements_selector: ".lazy"
    /* more options? */
});
```
