### ISSUE TITLE
Got data-was-processed true and src already set, but didn't get loaded class

### ISSUE THREAD

**Issue by ariona** [verlok/lazyload#238]
* What is happening?
I get the `data-was-processed="true"` and the `src` attribute set to the original image. But the class is still `initial` or `loading`.

* What is the expected behaviour?
Got the `loaded` class

* Which version of LazyLoad are you using?
vanilla-lazyload@8.15.0

* In which browser(s) and browser version(s) are you experiencing the problem?
Chrome  68.0.3440.106

* Could you provide the HTML, CSS and JS code you use for your images?
```html
<figure class="event__image">
	<a href="#">
		<span class="mm-lazyload" style="padding-bottom:53.07%">
			<img src="assets/images/dummy/event-1.jpg" alt="" />
		</span>
	</a>
</figure> <!-- .event__image -->
```
```css
.mm-lazyload{
	position: relative;
	display: block;
	background-image: url(../images/loader.gif);
	background-repeat: no-repeat;
	background-position: center;

	img{
		position: absolute;
		width: 100%;
		height: 100%;
		left: 0;
		top: 0;
		opacity: 0;
		transition: opacity $duration $timing;

		&.loaded{
			opacity: 1;
		}
	}
}
```
```js
var lazyloadImg = new LazyLoad({
    elements_selector: ".mm-lazyload img",
    callback_error: function(error){
    	console.log(error)
    }
});
```

* What are the steps to reproduce the problem?
I have 1 block of them on different section, the first section is loaded successfully and got the loaded class, but the second block only got the `data-was-processed="true"`, no loaded class.

By the way initializing on background-image didn't get the loaded class either.

Thanks.
