### ISSUE TITLE
data-bg - multiple sizes

### ISSUE THREAD

**Issue by laraduarte** [verlok/lazyload#457]
Hi,

Is it possible to have background images by screen resolution as we do with src?
` 
<picture>
        <source media="(min-width: 768px)" data-srcset={fileDesktop}></source>
        <source media="(min-width: 650px)" data-srcset={data.fileTablet}></source>
        <source media="(min-width: 350px)" data-srcset={fileMobile}></source>
        <div class="lazy" data-src={fileMobile}></div>
</picture>
`

Thanks in advance

**Comment by laraduarte** [comment]
` <picture>
          <source media="(min-width: 768px)" data-srcset={this.props.data.fileDesktop}></source>
          <source media="(min-width: 650px)" data-srcset={this.props.data.fileTablet}></source>
          <source media="(min-width: 350px)" data-srcset={this.props.data.fileMobile}></source>
          <div class="lazy" data-src={this.props.data.fileMobile}></div>
 </picture>`

**Comment by laraduarte** [comment]
> Hi,
> 
> Is it possible to have background images by screen resolution as we do with src?
> 
> 
> 
> 
> 
> Thanks in advance

**Comment by verlok** [comment]
You can do that by having 3 separated `div` that you show/hide using CSS media queries. This script won’t load the ones that are not visible, and only load the visible one.

**Comment by verlok** [comment]
Your case would be something like.

HTML

```html
<div class="lazy lazy-desktop" data-bg={fileDesktop}></div>
<div class="lazy lazy-tablet" data-bg={data.fileTablet}></div>
<div class="lazy lazy-mobile" data-bg={fileMobile}></div>
```

SASS

```scss
.lazy-mobile{
  @media (min-width: 650px) {
    display: none;
  }
}

.lazy-tablet {
  @media (max-width: 649px), (min-width: 768px) {
    display: none;
  }
}

.lazy-desktop {
  @media (max-width: 767px) {
    display: none;
  }
}
```

Or, in regular CSS

```css
@media (min-width: 650px) {
  .lazy-mobile {
    display: none;
  }
}

@media (max-width: 649px), (min-width: 768px) {
  .lazy-tablet {
    display: none;
  }
}

@media (max-width: 767px) {
  .lazy-desktop {
    display: none;
  }
}
```

Then you can create a lazyload instance using the `lazy` class as elements selector

```js
new LazyLoad({ elements_selector: ".lazy" });
```
